name: redis-desktop-manager
version: 1
summary: Redis Desktop Manager
description: Cross-platform GUI management tool for Redis

grade: stable
confinement: devmode
base: core18

apps:
  rdm:
    command: desktop-launch $SNAP/opt/redis-desktop-manager/rdm
    desktop: usr/share/applications/rdm.desktop
    plugs: 
     - home
     - unity7
     - opengl
     - gsettings
     - network
     - network-bind
     - x11
     - desktop
     - desktop-legacy
parts:
  application:
    plugin: qmake
    source: .
    source-subdir: src
    qt-version: qt5
    after: [desktop-qt5]
    project-files: 
     - rdm.pro
    build-packages:
     - qt5-default
     - qtdeclarative5-dev
     - libqt5charts5-dev
    stage-packages:
     - qt5-default
     - libqt5qml5
     - libqt5quick5
     - qml-module-qtquick-controls
     - qml-module-qtquick-controls2 
     - qml-module-qt-labs-settings
     - qml-module-qtquick-dialogs
     - qml-module-qtquick-layouts
     - qml-module-qt-labs-folderlistmodel
     - qml-module-qtqml-models2
     - qml-module-qtcharts
