// <auto-generated />
using BlazorDemo.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorDemo.Api.Migrations
{
    [DbContext(typeof(BlazorDemoContext))]
    [Migration("20180730100843_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorDemo.Model.DataModel.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookTitle")
                        .IsRequired();

                    b.Property<string>("ISBN");

                    b.Property<string>("PublisherName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Book","BlazorDemo");

                    b.HasData(
                        new { Id = 1, BookTitle = "C#", ISBN = "12312", PublisherName = "Oreally" },
                        new { Id = 2, BookTitle = "dot net", ISBN = "781273", PublisherName = "Wrox" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
